# Lab 1 - Introduction and the K-Nearest Neighbors Algorithm

In this lab section, we will provide a quick introduction to the NumPy library to develop your own implementation of the K-Nearest Neighbors Algorithm.

Specifically, we will cover the following topics:

1.  NumPy Library
2. Implementation of the K-Nearest Neighbors Algorithm

The theoretical background for the first lab session is covered in the 2nd Chapter of the **"An Introduction to Statistical Learning"** book : https://www.statlearning.com/




# 1. The numpy library

Python is a high-level, interpreted programming language known for its readability and versatility. It is widely used in various domains, including web development, data analysis, machine learning, and scientific computing. Python has a large standard library and a vast ecosystem of third-party libraries and frameworks, making it a powerful tool for a wide range of tasks.

- `numpy`: a fundamental Python package for numerical operations, providing support for arrays and matrices, as well as mathematical functions. You can explore
      its [API documentation](https://numpy.org/doc/stable/reference/index.html).

## Import python libraries

In [1]:
import numpy as np

We will now go thought some basic functionality of numpy.
We advise the students to follow the numpy [User guide](https://numpy.org/doc/stable/user/index.html) for a more complete guide on numpy array

In [2]:
# 1. let define a numpy array
simple_array_1 = np.array([1,2,3,4,5,6])

In [3]:
# we can get the shape of an array
print("we can get the shape of the vector")
print("vector:", simple_array_1)
print("Result: ", simple_array_1.shape)

we can get the shape of the vector
vector: [1 2 3 4 5 6]
Result:  (6,)


## numpy has a simple api for make numerical operations

### 1. scalar operation

In [4]:
# 1. add a scalar to the vector
scalar_add_result = simple_array_1 + 1
print("Add 1 to the following numpy array:", simple_array_1)
print("Result: ", scalar_add_result)

Add 1 to the following numpy array: [1 2 3 4 5 6]
Result:  [2 3 4 5 6 7]


In [5]:
# 2. multiply with scalar
scalate_mut_result = simple_array_1 * 10
print("We can multiply the following array with 10:", simple_array_1)
print("Result: ", scalate_mut_result)

We can multiply the following array with 10: [1 2 3 4 5 6]
Result:  [10 20 30 40 50 60]


### 2. operation between different numpy arrays

we can also make operation between different numpy vector

In [6]:
# let define a second array
simple_array_2 = np.array([6,5,4,3,2,1])

let's make different operation between array

In [7]:
# subtract two vectors
sub_result = simple_array_1 - simple_array_2
print("Subtract two vectors:")
print("vector 1:", simple_array_1)
print("vector 2:", simple_array_2)
print("Result:", sub_result)

Subtract two vectors:
vector 1: [1 2 3 4 5 6]
vector 2: [6 5 4 3 2 1]
Result: [-5 -3 -1  1  3  5]


In [8]:
# multiply two vectors
mult_result = simple_array_1 * simple_array_2
print("Multiply two vectors")
print("vector 1:", simple_array_1)
print("vector 2:", simple_array_2)
print("Result:", mult_result)

Multiply two vectors
vector 1: [1 2 3 4 5 6]
vector 2: [6 5 4 3 2 1]
Result: [ 6 10 12 12 10  6]


we can also combine two vector 

In [9]:
concatenate_array = np.concatenate([simple_array_1, simple_array_2])
print("concatenate")
print("vector 1:", simple_array_1)
print("vector 2:", simple_array_2)
print("Result:")
print(concatenate_array)

concatenate
vector 1: [1 2 3 4 5 6]
vector 2: [6 5 4 3 2 1]
Result:
[1 2 3 4 5 6 6 5 4 3 2 1]


or stack two arrays, combining them along a specific axis to form a larger array.

In [10]:
stack_array = np.stack([simple_array_1, simple_array_2],axis=0)
print("stack array")
print("vector 1:", simple_array_1)
print("vector 2:", simple_array_2)
print("Result:")
stack_array

stack array
vector 1: [1 2 3 4 5 6]
vector 2: [6 5 4 3 2 1]
Result:


array([[1, 2, 3, 4, 5, 6],
       [6, 5, 4, 3, 2, 1]])

### Indexing
we can select specific items of the numpy array.

In [11]:
print("select the second item of numpy")
print("vector 1:", simple_array_1)
print("Result:", simple_array_1[2])

select the second item of numpy
vector 1: [1 2 3 4 5 6]
Result: 3


In [12]:
# select a subset of the vector
print("select a subset of the vector")
print("vector 1:", simple_array_1)
print("Result:", simple_array_1[2:])

select a subset of the vector
vector 1: [1 2 3 4 5 6]
Result: [3 4 5 6]


we can reverse an array

In [13]:
inverse_simple_array_1 = simple_array_1[::-1]
print("array 1: ", simple_array_1)
print("Inverse array 1: ", inverse_simple_array_1)

array 1:  [1 2 3 4 5 6]
Inverse array 1:  [6 5 4 3 2 1]


### build in numpy method
numpy provide a variety on different build in method that is very useful for data analyse and create complex operation

In [14]:
print("We can get the sum of an array")
print("Vector:", simple_array_2)
print("Result:", np.sum(simple_array_2))

We can get the sum of an array
Vector: [6 5 4 3 2 1]
Result: 21


In [15]:
print("We can get the power an array")
print("Vector:", simple_array_2)
print("Result:", np.power(simple_array_2,2))

We can get the power an array
Vector: [6 5 4 3 2 1]
Result: [36 25 16  9  4  1]


In [16]:
np.insert(simple_array_2,1,10)

array([ 6, 10,  5,  4,  3,  2,  1])

In [17]:
print("We can get the square root of an array")
print("Vector:", simple_array_2)
print("Result:", np.sqrt(simple_array_2))

We can get the square root of an array
Vector: [6 5 4 3 2 1]
Result: [2.44948974 2.23606798 2.         1.73205081 1.41421356 1.        ]


In [18]:
# calculate the mean of an array
print("We can get the mean value of a vector ")
print("Vector:", simple_array_1)
print("Result:", simple_array_1.mean())

We can get the mean value of a vector 
Vector: [1 2 3 4 5 6]
Result: 3.5


In [19]:
print("We can get the standard deviation of a vector ")
print("Vector:", simple_array_1)
print("Result:", simple_array_1.std())

We can get the standard deviation of a vector 
Vector: [1 2 3 4 5 6]
Result: 1.707825127659933


# 2-K-Nearest Neighbors Algorithm

In the following we will implement the K-Nearest Neighbors Algorithm.
First we have to create some data for the algorithm. We can do it using the numpy package

## Generate some data points

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import statistics


# Generate normally distributed data with mean 0 and standard deviation 1, 100 samples, 3 classes and 2 features.
n_samples=100
class_prob = [0.33, 0.33, 0.34]
x = np.random.normal(loc = 0.0, scale= 1.0, size = (n_samples, 2))
y = np.random.choice(3, p=class_prob, size=n_samples)


# Convert the feature array `x` to a DataFrame with columns 'feature1' and 'feature2'
x = pd.DataFrame(data=x, columns=['feature1', 'feature2'])

# Convert the target array `y` to a DataFrame with column 'target'
y = pd.DataFrame(data=y, columns=['target'])

# Combine the feature DataFrame and target DataFrame into a single DataFrame
data = pd.concat([x, y], axis=1)

# Display the first few rows of the combined DataFrame
data.head()

,feature1,feature2,target
0,-1.625701,0.092106,1
1,-1.042719,1.005258,0
2,1.261861,-0.106870,0
3,-0.915282,-1.158458,1
4,-0.463966,-0.919788,2


In [40]:

test = np.array([1, 2])
Delta = x - test
Delta

np.linalg.norm(Delta,axis=1)

array([3.24566851, 2.27205039, 2.12308117, 3.69380028, 3.2662456 ,
       1.73708484, 2.64499333, 1.45264438, 1.83417312, 3.25171552,
       1.6429848 , 2.69904941, 3.17319186, 1.90840941, 2.08234137,
       4.8297963 , 3.55101003, 1.56181126, 0.67495854, 3.32872213,
       2.97278434, 1.97364347, 3.74809923, 3.10768452, 0.76180436,
       2.92383505, 1.76994214, 1.94613874, 1.36510966, 5.01261784,
       1.55877901, 2.28558753, 2.509512  , 2.06814367, 2.69427793,
       2.35367364, 2.87678357, 4.20579022, 3.87196827, 3.50780097,
       2.400081  , 2.9260446 , 2.04660576, 0.88072936, 4.23589347,
       0.91067283, 2.21112441, 1.8007696 , 4.55916615, 1.90430155,
       2.72528109, 5.02570212, 3.3891775 , 2.81711081, 4.00942351,
       3.16866127, 1.97894194, 2.58335614, 2.18814654, 2.82620626,
       3.51458104, 2.35716402, 2.82688501, 1.19432453, 2.22858827,
       1.25442638, 2.60832114, 3.09189349, 1.52510356, 1.48910299,
       3.12601883, 1.63388137, 2.11552216, 3.01041024, 2.59488

## Visualize the  data

In [ ]:
palette = { 0:'green', 1:'blue', 2:'red'}

colors = ['r','darkgreen','b','c','m','y']

# Create a figure with specified size
fig = plt.figure(figsize=(15, 8))

# Create the scatter plot
sns.scatterplot(data=data, x='feature1', y='feature2', hue='target', 
                alpha=0.9, s=250, palette=palette)


# Add legend with proper labels
ax = fig.get_axes()[0]
handles, labels = ax.get_legend_handles_labels()
ax.legend(handles, labels, title='Class', title_fontsize='13', loc='upper right')

# Display the plot
plt.show()

## Randomly create a new data point or test data

In [ ]:
# Generate a random value for x1 within the range of feature1
x1 = random.uniform(data.feature1.min(), data.feature1.max())

# Generate a random value for x2 within the range of feature2
x2 = random.uniform(data.feature2.min(), data.feature2.max())

# Create the test point
test_data = np.array([x1, x2])

# Create the scatter plot
fig = plt.figure(figsize=(15, 8))
sns.scatterplot(data=data, x='feature1', y='feature2', hue='target', 
                alpha=0.9, s=250, palette=palette)

plt.scatter(x=x1, y=x2, s=250, marker='*', color='k', label='test_data')

# Add legend with proper labels
handles, labels = plt.gca().get_legend_handles_labels()
plt.legend(handles, labels, title='Class', title_fontsize='13', loc='upper right')

# Set titles for x and y axes
plt.xlabel('Feature 1', fontsize=14)
plt.ylabel('Feature 2', fontsize=14)

# Display the plot
plt.show()


## KNN Implementation

 Euclidian distance Implementation

Create a function that calculate the euclidian distance between 2 data point by filling the bellow code.

$$
 \Large d(x,y) = \sqrt{\sum_{i=1}^{n}(x_i - y_i)^2}
$$

In [ ]:
def calculate_euclidean_distance(x1,x2, data):
    """
    TO DO
    Calculate the Euclidean distance between a given point and all points in the dataset.
    
    - (x1,x2) is the test point (mentionned early)
    - data is the data points, including only the x [if not, you need to remove the y]
    
    - you can use np.linalg.norm(..., axis=1)  which includes squaring the differences, 
    summing them up, and taking the square root
    
    - The output is an array containing the distance between each data point and the test point
    """
    
    return euclidean_distance

In [ ]:
# Uncomment and run the next lines to test your function Test you function 

distances= calculate_euclidean_distance(x1,x2, x)
#distances


Find the indices of the k-nearest neighbors of test_data in data_x

In [ ]:
def get_k_nearest_neighbors(euclidean_distances, k):
    """
    TO DO
    Get the indices of the k-nearest neighbors based on sorted distances.
    
    You can use np.argsort() of the euclidean_distances
    """
    
    return sorted_indices[:k]

In [ ]:
# Uncomment and run the next lines to test your function Test you function

#k_nearest_indices = get_k_nearest_neighbors(distances, k=5)
#k_nearest_indices

plot the nearest points

In [ ]:
def plot_knn(data, k, x1, x2, k_nearest_indices):
    """
    Plot the dataset, highlighting the k-nearest neighbors and the test point.
    """
    # Plot the entire dataset
    fig = plt.figure(figsize=(15, 8))
    sns.scatterplot(data=data, x='feature1', y='feature2', hue='target', 
                    alpha=0.9, s=250, palette=palette)

    # Highlight the k-nearest neighbors
    for i in k_nearest_indices:
        plt.scatter(x=data['feature1'][i], y=data['feature2'][i], s=250, alpha=0.6, linewidth=2, edgecolor='k',
                    color='orange')

    # Highlight the test point
    plt.scatter(x=x1, y=x2, s=400, marker='*', color='k')
    
    plt.title(f'K-Nearest Neighbor with K = {k}', fontsize=14)
    plt.xlabel('Feature 1')
    plt.ylabel('Feature 2')
    plt.legend(title='Target')
    plt.show()

Put everything in one function and Predict the class of the test data_x based on k-nearest neighbors


In [ ]:
def knn_algorithm(data, k, x1, x2):
    """
    TO DO
    Perform K-Nearest Neighbors algorithm and plot the results.
    """
    #TO DO Compute the euclidean distances
    euclidean_distances = 
    
    # TO DO Get k-nearest neighbors
    k_nearest_indices = ?
    
    # Determine the most common label among the k-nearest neighbors
    nearest_labels = data['target'].iloc[k_nearest_indices]
    prediction = statistics.mode(nearest_labels)
    
    # TO DO Plot the results
    ??
    
    return f'Predicted label: {prediction}'

In [ ]:
# Test your funtion here and determine the predicted class, You can test with different values of k and analyze.

#predicted_class= knn_algorithm(data, k=5, x1=x1, x2=x2)
#print(predicted_class)